### PR TITLE
Initial Landing page

### LINKED ISSUE #5: Create landing page

### PR DESCRIPTION
**Pull request by HarryET**
fixes #5

### CODE REVIEW

**Comment by HarryET** [comment]
@Isaiah-Hamilton Does the vertical height act weird for you?

**Comment by Isaiah-Hamilton** [comment]
> @Isaiah-Hamilton Does the vertical height act weird for you?

no

**Comment by Isaiah-Hamilton** [comment]
the image is a little big though

**Comment by HarryET** [comment]
Screenshot 2021-12-08 at 22 36 56
There is a scroll bar which could be fixed? @Isaiah-Hamilton

**Comment by HarryET** [comment]
This also needs the header on it!

**Review by Isaiah-Hamilton — APPROVED** [review]

**Pull request merged**
